<?php

namespace ContainerXxFmU0G;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ER0fjB0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eR0fjB0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eR0fjB0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.djBiB42', 'get_ServiceLocator_DjBiB42Service', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.JMt5F1x', 'get_ServiceLocator_JMt5F1xService', true],
            'App\\Controller\\UserController::new_user' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.djBiB42', 'get_ServiceLocator_DjBiB42Service', true],
            'App\\Controller\\VehiculeController::delete' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'App\\Controller\\VehiculeController::index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\VehiculeController::new_vehicule' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\VehiculeController::update' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.djBiB42', 'get_ServiceLocator_DjBiB42Service', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.JMt5F1x', 'get_ServiceLocator_JMt5F1xService', true],
            'App\\Controller\\UserController:new_user' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.djBiB42', 'get_ServiceLocator_DjBiB42Service', true],
            'App\\Controller\\VehiculeController:delete' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'App\\Controller\\VehiculeController:index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\VehiculeController:new_vehicule' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\VehiculeController:update' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new_user' => '?',
            'App\\Controller\\UserController::update' => '?',
            'App\\Controller\\VehiculeController::delete' => '?',
            'App\\Controller\\VehiculeController::index' => '?',
            'App\\Controller\\VehiculeController::new_vehicule' => '?',
            'App\\Controller\\VehiculeController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new_user' => '?',
            'App\\Controller\\UserController:update' => '?',
            'App\\Controller\\VehiculeController:delete' => '?',
            'App\\Controller\\VehiculeController:index' => '?',
            'App\\Controller\\VehiculeController:new_vehicule' => '?',
            'App\\Controller\\VehiculeController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
