<?php

namespace ContainerVP0eoCi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_96pIwWMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.96pIwWM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.96pIwWM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::delete' => ['privates', '.service_locator.nE4lZp0', 'get_ServiceLocator_NE4lZp0Service', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.Qyz7DBH', 'get_ServiceLocator_Qyz7DBHService', true],
            'App\\Controller\\AdminController::new_user' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminController::update' => ['privates', '.service_locator.nE4lZp0', 'get_ServiceLocator_NE4lZp0Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\VehiculeController::delete' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'App\\Controller\\VehiculeController::index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\VehiculeController::new_vehicule' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\VehiculeController::update' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:delete' => ['privates', '.service_locator.nE4lZp0', 'get_ServiceLocator_NE4lZp0Service', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.Qyz7DBH', 'get_ServiceLocator_Qyz7DBHService', true],
            'App\\Controller\\AdminController:new_user' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminController:update' => ['privates', '.service_locator.nE4lZp0', 'get_ServiceLocator_NE4lZp0Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\VehiculeController:delete' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'App\\Controller\\VehiculeController:index' => ['privates', '.service_locator.TX9pF9B', 'get_ServiceLocator_TX9pF9BService', true],
            'App\\Controller\\VehiculeController:new_vehicule' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\VehiculeController:update' => ['privates', '.service_locator.PJ1OMog', 'get_ServiceLocator_PJ1OMogService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::delete' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::new_user' => '?',
            'App\\Controller\\AdminController::update' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\VehiculeController::delete' => '?',
            'App\\Controller\\VehiculeController::index' => '?',
            'App\\Controller\\VehiculeController::new_vehicule' => '?',
            'App\\Controller\\VehiculeController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:delete' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:new_user' => '?',
            'App\\Controller\\AdminController:update' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\VehiculeController:delete' => '?',
            'App\\Controller\\VehiculeController:index' => '?',
            'App\\Controller\\VehiculeController:new_vehicule' => '?',
            'App\\Controller\\VehiculeController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
