<?php

namespace ContainerPUkLw7r;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UTPlg5dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uTPlg5d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uTPlg5d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.uTPlg5d.App\\Entity\\UserAdmin', NULL, 'Cannot autowire service ".service_locator.uTPlg5d": it needs an instance of "App\\Entity\\UserAdmin" but this type has been excluded in "config/services.yaml".'],
        ], [
            'manager' => '?',
            'user' => 'App\\Entity\\UserAdmin',
        ]);
    }
}
