<?php

namespace ContainerPUkLw7r;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdmin2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uTPlg5d.App\Entity\UserAdmin' shared service.
     *
     * @return \App\Entity\UserAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uTPlg5d": it needs an instance of "App\\Entity\\UserAdmin" but this type has been excluded in "config/services.yaml".');
    }
}
