<?php

namespace ContainerHGxwWL9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V8QREU3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v8QREU3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v8QREU3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'useradminRepository' => ['privates', 'App\\Repository\\UserAdminRepository', 'getUserAdminRepositoryService', true],
        ], [
            'em' => '?',
            'useradminRepository' => 'App\\Repository\\UserAdminRepository',
        ]);
    }
}
