<?php

namespace ContainerHGxwWL9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPasswordTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AdminPasswordType' shared autowired service.
     *
     * @return \App\Form\AdminPasswordType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AdminPasswordType.php';

        return $container->privates['App\\Form\\AdminPasswordType'] = new \App\Form\AdminPasswordType();
    }
}
